#!/usr/bin/env php
<?php

require_once "vendor/autoload.php";
require_once "autoload.php";

use \Pebble\Config;
use Pebble\DB\Helpers;

// Load config settings
Config::readConfig('./config');

// Load config settings
Config::readConfig('./config-locale');

$db = Config::getSection('DB');
$ary = Helpers::parsePDOString($db['url']);

echo $command = "mysql -u $db[username] -p$db[password] -h$ary[host] $ary[dbname]";
proc_close(proc_open($command, array(0 => STDIN, 1 => STDOUT, 2 => STDERR), $pipes));
