#!/usr/bin/env php
<?php

use Diversen\Translate\GoogleTranslate;
use Diversen\Translate\Extractor;

include_once "vendor/autoload.php";

putenv("GOOGLE_APPLICATION_CREDENTIALS=config-locale/pebble-2c949028ebcc.json");

// Extract first
$e = new extractor();
$e->defaultLanguage ='en';
$e->setSingleDir("www/App");
$e->updateLang();

// Extract using google
$t = new GoogleTranslate();
$t->target = 'da'; // danish
$t->source = 'en';

$t->setSingleDir("www/App");
$t->updateLang();
