SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `acl`;

DROP TABLE IF EXISTS `auth`;

DROP TABLE IF EXISTS `auth_cookie`;

DROP TABLE IF EXISTS `cache_system`;

DROP TABLE IF EXISTS `task`;

DROP TABLE IF EXISTS `time`;

DROP TABLE IF EXISTS `project`;

DROP TABLE IF EXISTS `acl_2`;